Repository elastic/elastic-agent-autodiscover, pull requests merged in 2022-09, with the labels that each got.

#26 Add StorageClass resource in k8s informer
  kubernetes/informer.go
  kubernetes/types.go
Labels: Team:Cloudnative-Monitoring

#27 jjbb: use fleet-ci
  .ci/jobs/defaults.yml
  .ci/jobs/elastic-agent-autodiscover-mbp.yml
Labels: Team:Automation, automation

#28 [automation] Update go release version 1.18.6
  .go-version
  .golangci.yml
Labels: automation, dependency
