Repository elastic/elastic-agent-autodiscover, pull requests merged in 2022-06, with the labels that each got.

#16 Fix go version in CI
  .ci/Jenkinsfile
  go.mod
  go.sum
  magefile.go
  tools/tools.go
Labels: Team:Elastic-Agent-Data-Plane

#15 [automation] Update go release version 1.17.11
  .go-version
  .golangci.yml
Labels: automation, dependency

#17 Synchronize lint rules across repositories
  .golangci.yml
  dev-tools/templates/.golangci.yml
  kubernetes/metadata/pod_test.go
Labels: Team:Elastic-Agent-Data-Plane

#20 Move hints helpers under utils and add tests
  utils/hints.go
  utils/hints_test.go
Labels: Team:Cloudnative-Monitoring
